baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Nathan Fishel'
theme = "gokarna"
pygmentsStyle = "monokai"

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 1

  [[menu.main]]
    # Unique identifer for a menu item
    identifier = "posts"
    url = "/posts/"   
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # Display name
    name = "Posts"
    # Weights are used to determine the ordering
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com"
    weight = 4
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"

[params]
  # URL for the avatar on homepage
  avatarURL = "/Users/nfishel/Documents/Personal-site/NateFishel/images/avatar.jpg"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-l"

  # Description to display on homepage
  description = "Sky above, sand below & peace within"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "gokarna", "hugo", "Nathaniel", "Fishel"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  #showPostsOnHomePage = "do not display"

  # Footer text
  footer = "Nathan Fishel"

  socialIcons = [
      {name = "linkedin", url = "https://www.linkedin.com/in/nathaniel-f-722a72165/"},
      {name = "github", url = "https://github.com/nfishel48"},
    ]

    
